groups:
  # Default reviewers for all pull requests.
  # Usually, at least on of the maintainers should approve PR before merging.
  # The best is if two maintainers do that.
  - name: maintainers # name of the group
    reviewers: 2 # how many reviewers do you want to assign?
    internal_reviewers: 2 # how many reviewers do you want to assign when the PR author belongs to this group?
    usernames: # github usernames of the reviewers
      - bmagyar
      - destogl
      - christophfroehlich
      - saikishor

  # Reviewers group to get broader feedback.
  - name: reviewers
    reviewers: 5
    usernames:
      - anfemosa
      - aprotyas
      - ARK3r
      - arne48
      - bijoua29
      - DasRoteSkelett
      - erickisos
      - fmauch
      - harderthan
      - homalozoa
      - livanov93
      - LukasMacha97
      - mamueluth
      - Maverobot
      - mcbed
      - mhubii
      - moriarty
      - olivier-stasse
      - progtologist
      - qiayuanl
      - rosterloh
      - VX792
      - xguay
