groups:
  # Default reviewers for all pull requests.
  # Usually, at least one of the maintainers should approve PR before merging.
  # The best is if two maintainers do that.
  - name: maintainers # name of the group
    reviewers: 2 # how many reviewers do you want to assign?
    internal_reviewers: 2 # how many reviewers do you want to assign when the PR author belongs to this group?
    usernames: # github usernames of the reviewers
      - bmagyar
      - christophfroehlich
      - destogl
      - MarqRazz
      - saikishor

  # Reviewers group to get broader feedback.
  - name: reviewers
    reviewers: 3
    usernames:
      - aprotyas
      - arne48
      - bijoua29
      - erickisos
      - fmauch
      - homalozoa
      - Juliaj
      - mamueluth
      - Maverobot
      - mhubii
      - moriarty
      - xguay
