---
name: Build and publish debian docker images

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/build_and_publish_debian_docker.yaml'
      - 'ros2_debian/**'
  schedule:
    - cron: '0 1 * * MON'

jobs:
  build_images_debian11:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        ros_distro: ['humble']
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          push: true
          file: Dockerfile.debian11
          tags: ghcr.io/${{ github.repository_owner }}/ros:${{ matrix.ros_distro }}-debian
          build-args: |
            ROS_DISTRO=${{ matrix.ros_distro }}
  build_images_debian12:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        ros_distro: ['jazzy', 'rolling']
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          push: true
          file: Dockerfile.debian12
          tags: ghcr.io/${{ github.repository_owner }}/ros:${{ matrix.ros_distro }}-debian
          build-args: |
            ROS_DISTRO=${{ matrix.ros_distro }}
