---
name: Build and publish debian docker images

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/build_and_publish_debian_docker.yaml'
      - 'ros2_debian/**'
  schedule:
    - cron: '0 1 * * MON'

jobs:
  build_images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - ros_distro: 'humble'
            debian_version: 'debian11'
          - ros_distro: 'jazzy'
            debian_version: 'debian12'
          - ros_distro: 'kilted'
            debian_version: 'debian12'
          - ros_distro: 'rolling'
            debian_version: 'debian12'
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ros2_debian
          push: true
          file: ros2_debian/Dockerfile.${{ matrix.debian_version }}
          tags: ghcr.io/${{ github.repository_owner }}/ros:${{ matrix.ros_distro }}-debian
          build-args: |
            ROS_DISTRO=${{ matrix.ros_distro }}
