name: Pre-commit

on:
  workflow_dispatch:
  pull_request:

jobs:
  pre-commit:
    uses: ./.github/workflows/reusable-pre-commit.yml
    with:
      ros_distro: rolling
      container: ubuntu:24.04
