name: Humble Stack Build
# author: Denis Štogl <denis@stoglrobotics.de>
# description: 'Build & test all dependencies from released (binary) packages.'

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/humble-binary-build.yml'
      - '.github/workflows/reusable-industrial-ci-with-cache.yml'
      - 'ros_controls.humble.repos'
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '03 1 * * *'

jobs:
  stack-build:
    uses: ./.github/workflows/reusable-industrial-ci-with-cache.yml
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [humble]
        ROS_REPO: [main, testing]
    with:
      ros_distro: ${{ matrix.ROS_DISTRO }}
      ros_repo: ${{ matrix.ROS_REPO }}
      target_workspace: ros_controls.${{ matrix.ROS_DISTRO }}.repos
      ref_for_scheduled_build: master
