name: Unstable from Rolling Stack Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '03 1 * * *'

jobs:
  stack-build:
    uses: ./.github/workflows/reusable-industrial-ci-with-cache.yml
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [iron]
        ROS_REPO: [main, testing]
    with:
      ros_distro: ${{ matrix.ROS_DISTRO }}
      ros_repo: ${{ matrix.ROS_REPO }}
      target_workspace: ros_controls.unstable-from-rolling.repos
      ref_for_scheduled_build: master
      rosdep_skip_keys: gazebo_ros2_control
