name: Jazzy Stack Build
# author: Christoph Froehlich <christoph.froehlich@ait.ac.at>
# description: 'Build & test all dependencies from released (binary) packages.'

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/jazzy-binary-build.yml'
      - '.github/workflows/reusable-industrial-ci-with-cache.yml'
      - 'ros_controls.jazzy.repos'
  push:
    branches:
      - master
    paths:
      - '.github/workflows/jazzy-binary-build.yml'
      - '.github/workflows/reusable-industrial-ci-with-cache.yml'
      - 'ros_controls.jazzy.repos'
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '03 1 * * *'

jobs:
  stack-build:
    uses: ./.github/workflows/reusable-industrial-ci-with-cache.yml
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [jazzy]
        ROS_REPO: [main, testing]
    with:
      ros_distro: ${{ matrix.ROS_DISTRO }}
      ros_repo: ${{ matrix.ROS_REPO }}
      target_workspace: ros_controls.${{ matrix.ROS_DISTRO }}.repos
      ref_for_scheduled_build: master
