name: Reusable ROS 2 Lint workflow
# Reusable action to simplify dealing with ros-linting
# author: Christoph Froehlich <christoph.froehlich@ait.ac.at>

on:
  workflow_call:
    inputs:
      ros_distro:
        description: 'ROS2 distribution name'
        required: true
        type: string
      os_name:
        description: 'On which OS to run the linter'
        required: false
        default: 'ubuntu-latest'
        type: string

env:
  # this will be src/{repo-owner}/{repo-name}
  path: src/${{ github.repository }}

jobs:
  ament_lint:
    name: ament_${{ matrix.linter }}
    runs-on: ${{ inputs.os_name }}
    strategy:
      fail-fast: false
      matrix:
          linter: [copyright, lint_cmake]
    steps:
    - uses: actions/checkout@v4
      with:
        path: ${{ env.path }}
    - uses: ros-tooling/setup-ros@v0.7
    - id: package_list_action
      uses: ros-controls/ros2_control_ci/.github/actions/set-package-list@ci_lint
      with:
        path: ${{ env.path }}
    - uses: ros-tooling/action-ros-lint@v0.1
      with:
        distribution: ${{ inputs.ros_distro }}
        linter: ${{ matrix.linter }}
        package-name: ${{ steps.package_list_action.outputs.package_list }}

  ament_lint_100:
    name: ament_cpplint
    runs-on: ${{ inputs.os_name }}
    steps:
    - uses: actions/checkout@v4
      with:
        path: ${{ env.path }}
    - uses: ros-tooling/setup-ros@v0.7
    - id: package_list_action
      uses: ros-controls/ros2_control_ci/.github/actions/set-package-list@ci_lint
      with:
        path: ${{ env.path }}
    - uses: ros-tooling/action-ros-lint@v0.1
      with:
        distribution: ${{ inputs.ros_distro }}
        linter: cpplint
        arguments: "--linelength=100 --filter=-whitespace/newline"
        package-name: ${{ steps.package_list_action.outputs.package_list }}

  ament_cppcheck:
    name: ament_cppcheck
    runs-on: ${{ inputs.os_name }}
    env:
      AMENT_CPPCHECK_ALLOW_SLOW_VERSIONS: true
    steps:
    - uses: actions/checkout@v4
      with:
        path: ${{ env.path }}
    - uses: ros-tooling/setup-ros@0.7.1
    - id: package_list_action
      uses: ros-controls/ros2_control_ci/.github/actions/set-package-list@ci_lint
      with:
        path: ${{ env.path }}
    - uses: ros-tooling/action-ros-lint@v0.1
      with:
        distribution: ${{ inputs.ros_distro }}
        linter: cppcheck
        arguments: "--language=c++"
        package-name: ${{ steps.package_list_action.outputs.package_list }}
