name: Reusable Windows Binary Build
# author: Christoph Froehlich <christoph.froehlich@ait.ac.at>

on:
  workflow_call:
    inputs:
      ros_distro:
        description: "ROS 2 distribution name, e.g. rolling"
        required: true
        type: string
      ref_for_scheduled_build:
        description: "Reference on which the repo should be checkout for scheduled build. Usually is this name of a branch or a tag."
        default: ""
        required: false
        type: string
      os_name:
        description: "On which OS to run the build job"
        required: false
        default: "windows-2022"
        type: string
      container:
        description: "Docker container to run the job in, e.g. ubuntu:noble"
        required: false
        default: ""
        type: string
      pixi_dependencies:
        description: "Space-separated list of additional pixi dependencies"
        required: false
        default: ""
        type: string
      windows_dependencies:
        description: "Path to a repos file with additional windows dependencies"
        required: false
        default: ""
        type: string
      target_workspace:
        description: 'Path to local .repos file for target workspace.'
        default: ''
        required: false
        type: string
      skip_dependencies:
        description: "Space-separated list of packages to skip from rosinstall_generator dependency resolution"
        default: "sdformat_urdf eigenpy hpp-fcl"
        required: false
        type: string
      skip_packages:
        description: "Space-separated list of packages to skip from build"
        default: ""
        required: false
        type: string
      skip_packages_regex:
        description: "Regex for packages to skip from build"
        default: ""
        required: false
        type: string
      ninja_packages:
        description: "Space-separated list of packages to be built with Ninja generator (default is MSVC otherwise)"
        default: ""
        required: false
        type: string
      upstream_cmake_args:
        description: "Additional arguments to pass to CMake for upstream workspace, e.g. -DBUILD_TESTING=OFF"
        default: "-DBUILD_TESTING=OFF"
        required: false
        type: string
      target_cmake_args:
        description: "Additional arguments to pass to CMake for target workspace, e.g. -DBUILD_TESTING=OFF"
        default: ""
        required: false
        type: string
      ccache_dir:
        description: "Local path to store ccache (from github.workspace)."
        default: ".ccache"
        required: false
        type: string

jobs:
  reusable_ros_tooling_source_build:
    name: ${{ inputs.ros_distro }} ${{ inputs.os_name }}
    if: ${{ !(github.event_name == 'pull_request' && contains(join(github.event.pull_request.labels.*.name, ','), 'conflicts')) }}
    runs-on: ${{ inputs.os_name }}
    container: ${{ inputs.container }}
    env:
      ros_underlay_path: C:\dev
      upstream_workspace: C:\upstream_ws
      target_workspace: C:\target_ws
      # this will be src/{repo-owner}/{repo-name}
      repo_path: src/${{ github.repository }}
      tooling_repo_path: src/ros-controls/ros2_control_ci
      CCACHE_DIR: ${{ github.workspace }}/${{ inputs.ccache_dir }}
      CACHE_PREFIX: win-${{ inputs.ros_distro }}-${{ inputs.target_workspace }}-${{ github.job }}
      CCACHE_MSVC: "1"
    steps:
      - name: Checkout default ref when build is not scheduled
        if: ${{ github.event_name != 'schedule' }}
        uses: actions/checkout@v6
        with:
          path: ${{ env.repo_path }}
      - name: Checkout ${{ inputs.ref_for_scheduled_build }} on scheduled build
        if: ${{ github.event_name == 'schedule' }}
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref_for_scheduled_build }}
          path: ${{ env.repo_path }}

      - name: Checkout ros2_control_ci tooling scripts
        if: ${{ github.repository != 'ros-controls/ros2_control_ci' }}
        uses: actions/checkout@v6
        with:
          repository: ros-controls/ros2_control_ci
          ref: master
          path: ${{ env.tooling_repo_path }}

      - name: Restore pixi.lock
        uses: actions/cache/restore@v5
        id: cache
        with:
          path: pixi.lock
          key: pixi|${{ inputs.ros_distro }}

      - name: Bootstrap pixi and patch manifest file
        # https://docs.ros.org/en/rolling/Installation/Windows-Install-Binary.html
        run: |
          $manifest = "pixi.toml"
          irm https://raw.githubusercontent.com/ros2/ros2/refs/heads/rolling/pixi.toml -OutFile $manifest

          $deps = "${{ inputs.pixi_dependencies }} rosinstall_generator ccache"
          . "${{ env.tooling_repo_path }}\scripts\Update-PixiManifest.ps1"
          Update-PixiManifestDependencies -ManifestPath $manifest -Dependencies $deps

      - name: Install pixi
        uses: prefix-dev/setup-pixi@v0.9.4
        # Cache pixi environment only on default branch to save disk space
        with:
          cache: ${{ steps.cache.outputs.cache-hit == 'true' }} # only use cache if pixi.lock is present
          cache-write: ${{ steps.cache.outputs.cache-hit == 'true' && github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }} # only write cache on push to default branch to save disk space, caches from PRs can't be accessed anyways; only allowed if pixi.lock is present
          locked: false

      - name: Cache pixi.lock
        uses: actions/cache/save@v5
        # independent of the success of the following steps, but only on default branch
        # cache independent of the cache hit of the restore step, because pixi.toml could have changed
        if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        with:
          path: pixi.lock
          key: pixi|${{ inputs.ros_distro }}

      - name: Upload pixi lock file
        uses: actions/upload-artifact@v7
        with:
          name: pixi.lock
          path: pixi.lock

      - name: Install ROS
        # Download and extract ROS 2 package and patch paths, see
        # https://docs.ros.org/en/rolling/Installation/Windows-Install-Binary.html
        # Note: We don't use the shipped pixi.toml file, we generated our own above
        run: |
          Invoke-Expression ((& pixi shell-hook -s powershell) -join "`n")

          New-Item -ItemType Directory -Force -Path ${{ env.ros_underlay_path }}
          Set-Location -Path ${{ env.ros_underlay_path }}
          $url = "https://github.com/ros2/ros2/releases/download/release-rolling-nightlies/ros2-rolling-nightly-windows-amd64.zip"
          $output = "ros2-package-windows-AMD64.zip"
          Invoke-WebRequest -Uri $url -OutFile $output
          Expand-Archive -Path $output -DestinationPath ros2_${{ inputs.ros_distro }}
          Remove-Item $output
          Set-Location -Path ros2_${{ inputs.ros_distro }}\ros2-windows
          python preinstall_setup_windows.py

      - name: Get package list
        id: package_list_action
        uses: ros-controls/ros2_control_ci/.github/actions/set-package-list-pixi@master
        with:
          path: ${{ env.repo_path }}
          manifest-path: pixi.toml

      - name: Prepare target workspace
        if: ${{ inputs.target_workspace != '' }}
        run: |
          Invoke-Expression ((& pixi shell-hook -s powershell) -join "`n")

          mkdir -p ${{ env.target_workspace }}/src
          $repo_file = "${{ env.repo_path }}\${{ inputs.target_workspace }}"
          if (Test-Path "$repo_file") {
            vcs import --input $repo_file ${{ env.target_workspace }}/src
            vcs log -l1 ${{ env.target_workspace }}/src
            New-Item -ItemType File -Path "${{ env.repo_path }}\COLCON_IGNORE" -Force | Out-Null
          }
      - name: Restore ccache folder
        uses: actions/cache/restore@v5
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ env.CACHE_PREFIX }}-${{ github.sha }}-${{ github.run_id }}
          restore-keys: |
            ccache-${{ env.CACHE_PREFIX }}-${{ github.sha }}
            ccache-${{ env.CACHE_PREFIX }}

      - name: Initialize ccache
        shell: cmd
        run: |
          call pixi shell-hook -s cmd > pixi_env.bat
          call pixi_env.bat >nul 2>&1

          if not exist "${{ env.CCACHE_DIR }}" mkdir "${{ env.CCACHE_DIR }}"
          set "CCACHE_WRAPPER=%RUNNER_TEMP:\=/%/cl_wrapper.bat"
          > "%CCACHE_WRAPPER%" echo @echo off
          >> "%CCACHE_WRAPPER%" echo ccache cl.exe %%*

          echo CCACHE wrapper created at: %CCACHE_WRAPPER%
          type "%CCACHE_WRAPPER%"
          ccache --show-config
          ccache --zero-stats

      - name: Clone dependencies
        run: |
          Invoke-Expression ((& pixi shell-hook -s powershell) -join "`n")
          ${{ env.ros_underlay_path }}\ros2_${{ inputs.ros_distro }}\ros2-windows\setup.ps1

          mkdir -p ${{ env.upstream_workspace }}/src
          $target_from_path = "${{ env.repo_path }}"
          if (![string]::IsNullOrWhiteSpace("${{ inputs.target_workspace }}")) {
            $target_from_path = "${{ env.target_workspace }}"
          }

          # check for repos files, and pass them to vcstool
          if (![string]::IsNullOrWhiteSpace("${{ inputs.windows_dependencies }}")) {
            $repo_file_win = "${{ env.repo_path }}\${{ inputs.windows_dependencies }}"
            if (Test-Path "$repo_file_win") {
              Write-Output "Windows repos file found"
              vcs import --input $repo_file_win ${{ env.upstream_workspace }}/src
            vcs log -l1 src
            }
          }

          # use rosinstall_generator to get all dependencies which are not yet installed
          $underlay_ws_pkgs=$(ros2 pkg list)
          # Write-Host "Packages in ROS installation: $underlay_ws_pkgs"
          $skip_regex_packages=@()
          $skip_regex_paths=@()
          if (![string]::IsNullOrWhiteSpace("${{ inputs.skip_packages_regex }}")) {
            $skip_regex_packages = @(colcon list --names-only --base-paths $target_from_path ${{ env.upstream_workspace }}/src |
              Select-String -Pattern "${{ inputs.skip_packages_regex }}" |
              ForEach-Object { $_.Line.Trim() } |
              Where-Object { $_ })

            if ($skip_regex_packages.Length -gt 0) {
              $skip_regex_paths = @(colcon list --paths-only --base-paths $target_from_path ${{ env.upstream_workspace }}/src --packages-select $skip_regex_packages)
            }

            Write-Host "Skipping packages from skip_regex_arg: $($skip_regex_packages -join ' ')"
            Write-Host "Skipping local paths via exclude-path: $($skip_regex_paths -join ' ')"
          }

          $skip_dependencies = @("${{inputs.skip_dependencies}}" -split '\s+' | Where-Object { $_ })
          $exclude_packages = @($underlay_ws_pkgs) + $skip_dependencies + $skip_regex_packages

          $rosinstall_args = @(
            '--rosdistro', '${{ inputs.ros_distro }}',
            '--deps',
            '--deps-only',
            '--format', 'repos'
          )

          if ($exclude_packages.Length -gt 0) {
            $rosinstall_args += '--exclude'
            $rosinstall_args += $exclude_packages
          }

          if ($skip_regex_paths.Length -gt 0) {
            $rosinstall_args += '--exclude-path'
            $rosinstall_args += $skip_regex_paths
          }

          $rosinstall_args += '--from-path'
          $rosinstall_args += @('${{ env.upstream_workspace }}', $target_from_path)

          $rosinstall_cmd = @('rosinstall_generator') + ($rosinstall_args | ForEach-Object {
            if ($_ -match '\s') {
              '"' + ($_ -replace '"', '\"') + '"'
            } else {
              $_
            }
          })
          Write-Host "Running command: $($rosinstall_cmd -join ' ')"

          & rosinstall_generator @rosinstall_args > deps.repos
          # rosinstall_generator skips excludes with are from a different repo (gbp instead of development repo)
          vcs import --skip-existing --input deps.repos ${{ env.upstream_workspace }}/src
          vcs log -l1 src

      - name: Upload repos file
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.package_list_action.outputs.repo_name }}.${{ inputs.ros_distro }}.windows.repos
          path: deps.repos

      - name: Build upstream workspace
        # use Ninja generator optionally for selected packages.
        # This is needed for RSL, but doesn't work for msg packages
        # https://github.com/search?q=repo%3APickNikRobotics%2FRSL%20ninja&type=code
        # https://github.com/colcon/colcon-ros/issues/84#issuecomment-1862881299
        shell: cmd
        run: |
          call pixi shell-hook -s cmd > pixi_env.bat
          call pixi_env.bat >nul 2>&1

          set "CCACHE_WRAPPER=%RUNNER_TEMP:\=/%/cl_wrapper.bat"
          call ${{ env.ros_underlay_path }}\ros2_${{ inputs.ros_distro }}\ros2-windows\setup.bat
          pushd ${{ env.upstream_workspace }}

          @echo on

          set skip_arg=
          if not "${{ inputs.skip_packages }}"=="" (
            set skip_arg=${{ inputs.skip_packages }}
          )

          set skip_regex_arg=
          if not "${{ inputs.skip_packages_regex }}"=="" (
            set skip_regex_arg=--packages-skip-regex "${{ inputs.skip_packages_regex }}"
          )

          if not "${{ inputs.ninja_packages }}"=="" (
            colcon build --packages-up-to ${{ inputs.ninja_packages }} --cmake-args -G Ninja -DCMAKE_C_COMPILER="%CCACHE_WRAPPER%" -DCMAKE_CXX_COMPILER="%CCACHE_WRAPPER%" --event-handler console_cohesion+ --merge-install
            if errorlevel 1 exit /b %errorlevel%
            set skip_arg=%skip_arg% ${{ inputs.ninja_packages }}
          )

          REM skip pinocchio, which take an eternity to build. build with different cmake args, see below
          colcon build --packages-skip pinocchio %skip_arg% %skip_regex_arg% --event-handler console_cohesion+ ^
            --cmake-args -DCMAKE_C_COMPILER="%CCACHE_WRAPPER%" -DCMAKE_CXX_COMPILER="%CCACHE_WRAPPER%" ${{ inputs.upstream_cmake_args }} ^
            --merge-install
          if errorlevel 1 exit /b %errorlevel%

          REM Check if 'pinocchio' is in the list of packages, and build it
          REM eigenpy and hpp-fcl is not needed with the used cmake args
          colcon list --names-only | findstr /R /C:"^pinocchio$" >nul
          if errorlevel 1 (
              REM pinocchio not present → do nothing but succeed
              exit /b 0
          ) else (
              colcon build ^
                --cmake-args --no-warn-unused-cli ^
                  -DBUILD_EXAMPLES=OFF -DBUILD_PYTHON_INTERFACE=OFF -DBUILD_WITH_HPP_FCL_SUPPORT=OFF ^
                  -DBUILD_WITH_COLLISION_SUPPORT=OFF ^
                  -DCMAKE_C_COMPILER="%CCACHE_WRAPPER%" -DCMAKE_CXX_COMPILER="%CCACHE_WRAPPER%" ^
                --packages-select pinocchio ^
                --merge-install
          )

      - name: Build target workspace
        id: build_target_workspace
        shell: cmd
        run: |
          call pixi shell-hook -s cmd > pixi_env.bat
          call pixi_env.bat >nul 2>&1

          set "CCACHE_WRAPPER=%RUNNER_TEMP:\=/%/cl_wrapper.bat"
          call ${{ env.ros_underlay_path }}\ros2_${{ inputs.ros_distro }}\ros2-windows\setup.bat
          call ${{ env.upstream_workspace }}\install\setup.bat

          @echo on

          set skip_arg=
          if not "${{ inputs.skip_packages }}"=="" (
            set skip_arg=--packages-skip ${{ inputs.skip_packages }}
          )
          set skip_regex_arg=
          if not "${{ inputs.skip_packages_regex }}"=="" (
            set skip_regex_arg=--packages-skip-regex "${{ inputs.skip_packages_regex }}"
          )
          if not "${{ inputs.target_workspace }}"=="" (
            pushd ${{ env.target_workspace }}
          )
          colcon build %skip_arg% %skip_regex_arg% --event-handler console_cohesion+ ^
            --cmake-args -DCMAKE_C_COMPILER="%CCACHE_WRAPPER%" -DCMAKE_CXX_COMPILER="%CCACHE_WRAPPER%" ${{ inputs.target_cmake_args }} ^
            --merge-install

      - name: Show ccache stats
        shell: cmd
        run: |
          call pixi shell-hook -s cmd > pixi_env.bat
          call pixi_env.bat >nul 2>&1

          ccache --show-stats

      - name: Save ccache folder
        if: ${{ always() && github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && steps.build_target_workspace.outcome == 'success' }}
        uses: actions/cache/save@v5
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ env.CACHE_PREFIX }}-${{ github.sha }}-${{ github.run_id }}
