name: RHEL Stack Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/rhel-stack-build.yml'
      - '.github/workflows/reusable-rhel-binary-build.yml'
      - 'ros_controls.humble.repos'
      - 'ros_controls.jazzy.repos'
      - 'ros_controls.kilted.repos'
      - 'ros_controls.rolling.repos'
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '42 4 * * MON-FRI'

concurrency:
  # cancel previous runs of the same workflow, except for pushes on given branches
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, 'refs/heads') }}

jobs:
  rhel_stack_build_gate:
    runs-on: ubuntu-latest
    outputs:
      skip_stack_build: ${{ steps.gate.outputs.skip_stack_build }}
    steps:
      - name: Evaluate stack build gate
        id: gate
        uses: ./.github/actions/stack-build-gate
        with:
          blocked_paths: |
            - '.github/workflows/build_and_publish_rhel_docker.yaml'
            - 'ros2_rhel/**'

  rhel_stack_build:
    needs: rhel_stack_build_gate
    if: ${{ needs.rhel_stack_build_gate.outputs.skip_stack_build != 'true' }}
    uses: ./.github/workflows/reusable-rhel-binary-build.yml
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [humble, jazzy, kilted, rolling]
    with:
      ros_distro: ${{ matrix.ROS_DISTRO }}
      target_workspace: ros_controls.${{ matrix.ROS_DISTRO }}.repos
      skip_packages_regex: '^mujoco_ros2_control.*$|^gz_ros2_control.*$|^ros2_control_demo_example_9$'
      ref_for_scheduled_build: master
