name: Check Rolling Compatibility on Kilted
# author: Christoph Froehlich <christoph.froehlich@ait.ac.at>
# description: 'Build & test the rolling stack on Kilted distro.'

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/rolling-compatibility-kilted-binary-build.yml'
      - '.github/workflows/reusable-industrial-ci-with-cache.yml'
      - 'ros_controls.rolling-on-kilted.repos'
  push:
    branches:
      - master
    paths:
      - '.github/workflows/rolling-compatibility-kilted-binary-build.yml'
      - '.github/workflows/reusable-industrial-ci-with-cache.yml'
      - 'ros_controls.rolling-on-kilted.repos'
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '03 1 * * *'

jobs:
  stack-build-on-kilted:
    uses: ./.github/workflows/reusable-industrial-ci-with-cache.yml
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [kilted]
        ROS_REPO: [main, testing]
    with:
      ros_distro: ${{ matrix.ROS_DISTRO }}
      ros_repo: ${{ matrix.ROS_REPO }}
      target_workspace: ros_controls.rolling-on-kilted.repos
      ref_for_scheduled_build: master
