name: Test contexts

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Github.job ${{ github.job }}"
          echo "Github.workflow ${{ github.workflow }}"
  call_reusable_test:
    uses: ./.github/workflows/reusable_test_contexts.yml
